services:
  frontend:
    platform: linux/arm64
    build:
      context: ./smart_app/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - seccomp:unconfined
    restart: always
    depends_on:
      - backend
    networks:
      - voting-network
    # volumes:
    #   - /ssl:/etc/nginx/ssl:ro

  backend:
    platform: linux/arm64
    hostname: backend
    build:
      context: ./smart_app/backend
      dockerfile: Dockerfile
    container_name: voting-system

    expose:
      - "5000"
    environment:
      - ENVIRONMENT=PRODUCTION
      - MONGO_URI=mongodb://mongo:27017/smart_voting_system
      - SECRET_KEY=your_secret
      - JWT_SECRET_KEY=your_jwt_secret

    depends_on:
      - mongo
    restart: always
    networks:
      - voting-network

  mongo:
    platform: linux/arm64
    image: mongo:7
    container_name: voting-system-mongo

    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - voting-network

volumes:
  mongo_data:

networks:
  voting-network:
    driver: bridge
