services:
  frontend:
    build:
      context: ./smart_app/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
      - "443:443"

    security_opt:
      - seccomp:unconfined
    restart: always
    depends_on:
      - backend_1
      - backend_2
      - backend_3
    networks:
      - voting-network

    mem_limit: 256m
    cpus: 0.50
    cpuset: "0-1"

  backend_1:
    build:
      context: ./smart_app/backend
    container_name: backend_1
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - voting-network

    mem_limit: 512m
    cpus: 1.0

  backend_2:
    build:
      context: ./smart_app/backend
    container_name: backend_2
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - voting-network

    mem_limit: 512m
    cpus: 1.0

  backend_3:
    build:
      context: ./smart_app/backend
    container_name: backend_3
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - voting-network

    mem_limit: 512m
    cpus: 1.0

  redis:
    image: redis:7-alpine
    container_name: voting-redis
    restart: always

    networks:
      - voting-network

    mem_limit: 256m
    cpus: 0.5

  mongo:
    image: mongo:7
    container_name: voting-system-mongo

    expose:
      - "27017"

    volumes:
      - mongo_data:/data/db
      - ./backup:/backup

    restart: always
    networks:
      - voting-network

    mem_limit: 1g
    cpus: 1.0
    cpuset: "0-3"

    command: ["mongod", "--wiredTigerCacheSizeGB=0.25"]

volumes:
  mongo_data:

networks:
  voting-network:
    driver: bridge
